version: '3.8'
services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      PORT: ${PORT:-3000}
      DB_HOST: mysql
      DB_USER: ${DB_USER:-freekds}
      DB_PASSWORD: ${DB_PASSWORD:-yourpassword}
      DB_NAME: ${DB_NAME:-kds_db}
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-kds_db}
      MYSQL_USER: ${DB_USER:-freekds}
      MYSQL_PASSWORD: ${DB_PASSWORD:-yourpassword}
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
volumes:
  db_data:
