services:
  app:
    build: .
    ports:
      - "${APP_HOST_PORT:-3000}:3000"
    restart: unless-stopped
    environment:
      PORT: ${PORT:-3000}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-freekds}
      DB_PASSWORD: ${DB_PASSWORD:-yourpassword}
      DB_NAME: ${DB_NAME:-kds_db}
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"\]
      interval: 30s
      timeout: 10s
      retries: 3
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-kds_db}
      MYSQL_USER: ${DB_USER:-freekds}
      MYSQL_PASSWORD: ${DB_PASSWORD:-yourpassword}
    ports:
      - "${DB_HOST_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      retries: 10
volumes:
  db_data:
