CREATE TABLE IF NOT EXISTS screen_definitions (
  station_id INT PRIMARY KEY,
  definition JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (station_id) REFERENCES stations(id) ON DELETE CASCADE
);
