CREATE TABLE IF NOT EXISTS api_tokens (
  id INT PRIMARY KEY AUTO_INCREMENT,
  token_id VARCHAR(36) NOT NULL,
  name VARCHAR(100) NOT NULL,
  secret_hash VARCHAR(255) NOT NULL,
  scopes JSON NOT NULL,
  station_id INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_used TIMESTAMP NULL DEFAULT NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  revoked TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE KEY uniq_token_id (token_id)
);

